server:
  port: 8082

temporal-config:
  host: '172.20.0.4'
  port: 7233

mongo-config:
  protocol: 'mongodb+srv'
  database: 'Cluster15382'
  password: 'hellorsatya'
  host: 'cluster15382.nl5hqoa.mongodb.net'
  props: 'retryWrites=true&w=majority'
  indexKey: '_id'
